In [156]:
from keras.models import load_model
import pickle
import pandas as pd
import tensorflow as tf
import numpy as np

In [157]:
with open('label_encoder.pkl', 'rb') as f:
    label_encoder = pickle.load(f)

In [158]:
with open('onehot_encoder.pkl', 'rb') as f:
    onehot_encoder = pickle.load(f)

In [159]:
with open('scaler.pkl', 'rb') as f:
    scaler = pickle.load(f)

In [160]:
model = load_model('titanic_model.keras')

In [161]:
# Pclass	Sex	SibSp	Parch	Fare	Embarked_Cherbourg	Embarked_Queenstown	Embarked_Southampton

In [162]:
# user = {'Pclass': 3,'Sex':'female','SibSp': 1,'Parch': 0,'Fare': 11,'Embarked':'Queenstown'}

In [163]:
user = {'Pclass': 1,'Sex':'male','SibSp': 2,'Parch': 0,'Fare': 76,'Embarked':'Cherbourg'}

In [164]:
user = pd.DataFrame([user])

In [165]:
user

   Pclass   Sex  SibSp  Parch  Fare   Embarked
0       1  male      2      0    76  Cherbourg

In [166]:
user['Sex'] = label_encoder.transform(user['Sex'])

In [167]:
user

   Pclass  Sex  SibSp  Parch  Fare   Embarked
0       1    1      2      0    76  Cherbourg

In [168]:
embarked = onehot_encoder.transform(user[['Embarked']])

In [169]:
embarked = pd.DataFrame(embarked, columns=onehot_encoder.get_feature_names_out())

In [170]:
embarked

   Embarked_Cherbourg  Embarked_Queenstown  Embarked_Southampton
0                 1.0                  0.0                   0.0

In [171]:
data = pd.concat([user.drop('Embarked', axis=1), embarked], axis=1)

In [172]:
data

   Pclass  Sex  ...  Embarked_Queenstown  Embarked_Southampton
0       1    1  ...                  0.0                   0.0

[1 rows x 8 columns]

In [173]:
data[['Pclass', 'SibSp', 'Parch', 'Fare']] = scaler.transform(data[['Pclass', 'SibSp', 'Parch', 'Fare']])

In [174]:
data

     Pclass  Sex  ...  Embarked_Queenstown  Embarked_Southampton
0 -1.568865    1  ...                  0.0                   0.0

[1 rows x 8 columns]

In [175]:
y = model.predict(data)

WARNING:tensorflow:6 out of the last 7 calls to <function TensorFlowTrainer.make_predict_function.<locals>.one_step_on_data_distributed at 0x76d824239bd0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.

WARNING:tensorflow:6 out of the last 7 calls to <function TensorFlowTrainer.make_predict_function.<locals>.one_step_on_data_distributed at 0x76d824239bd0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

In [176]:
y = y[0][0]

### Probability of Survival
Chance of survival of passenger is 0.65
- if model > 0.5 then --> Survived
- else --> Not Survived

In [177]:
if y > 0.5:
    print(f"Chance of survival of passenger is {y:.2f}")
    print("Passenger is likely to Survive")
else:
    print(f"Chance of survival of passenger is {y:.2f}")
    print("Passenger is likely to Not Survive")

Chance of survival of passenger is 0.39
Passenger is likely to Not Survive